### ISSUE TITLE
Issue with cursor teardrop on Samsung Dex

### ISSUE THREAD

**Issue by NSuknyarov** [deadlyjack/code-editor#111]
Hi, 
I've using this editor and I'd been very happy until recently.

The issue is that when I started using the editor months ago on samsung dex (it's a desktop mode for Android), there was no teardrop below the cursor and editor behaved as a desktop editor. Recently an update brought the teardop below the cursor, which was a bit annoying, but I was able to ignore it for the most part. But one of the most recent updates made the teardrop so big that it often hides information from the lower lines. 

![Screenshot_20201021-181909_Acode](https://user-images.githubusercontent.com/4368007/96742392-84121b00-13cb-11eb-8a45-25913184efbf.jpg)

Please fix this issue by bringing the old behaviour or adding an option to hide it. Literally there is no other options on Android, which is this close to a desktop experience!

**Comment by deadlyjack** [comment]
Thank you for reporting this issue. I'll fix this issue.

**Comment by deadlyjack** [comment]
Hi, thank you for reporting this issue. I've provided option to make teardrop small and to completely remove it.
