### ISSUE TITLE
Exit from application

### ISSUE THREAD

**Issue by blackeangel** [deadlyjack/code-editor#124]
add the ability to optionally issue a request to exit the application. What could be turned on or off in the settings.

**Comment by deadlyjack** [comment]
Please can you explain the. I'm unable to understand it.

**Comment by blackeangel** [comment]
> Please can you explain the. I'm unable to understand it.

Sure. If you press the Back button, you will receive an alert: "Close the application?"
I would like to see a switch in the settings so that you can close the application without this notification by double-clicking the back button.

**Comment by deadlyjack** [comment]
I've provided this option, it will be available in next version.
