### ISSUE TITLE
Menu 'Select word' not work

### ISSUE THREAD

**Issue by Micha-he** [deadlyjack/code-editor#131]
The menu 'Select word' not work.

Test procedure:
- Open lokal file
- Set cursor to a word
- Select menu 'Select word'
  (I can't see a selection)
- Select menu 'Copy'
- Select menu 'Paste'

The word under the cursor isn't insert !

**Comment by deadlyjack** [comment]
It's working perfectly. Please provide some video proof. Thank you.

**Comment by Micha-he** [comment]
It didn't work here. Tested with V1.1.14.138 too. The old clipboard isn't replaced and contain the old text.

**Comment by blackeangel** [comment]
> It didn't work here. Tested with V1.1.14.138 too. The old clipboard isn't replaced and contain the old text.

Work is good on V1.1.14.137

**Comment by Micha-he** [comment]
I've tested it with both versions. It didn't work and I can't find the reason.

**Comment by Micha-he** [comment]
It isn't work before in V137 and not in actual V138. But @blackeangel youre right ! After uninstall and reinstall the actual version, it is working now.

**Comment by Micha-he** [comment]
I've found the problem: If I set the cursor-controller to none, the selection not work anymore.
