### ISSUE TITLE
Feature request: Long touch to select

### ISSUE THREAD

**Issue by Micha-he** [deadlyjack/code-editor#132]
To select a word or a part of the text, it would be helpful to get a function to select text with two marker after a long-press to the text.

Like in this screenshot:
![Screenshot_20201119-174156](https://user-images.githubusercontent.com/36689516/99696666-3d2d4900-2a8f-11eb-969e-22f324e16592.jpg)

**Comment by deadlyjack** [comment]
To select word, tap on edit icon (✏) -> select word.

**Comment by Micha-he** [comment]
This function does not currently work (here) and how should I use it to mark part of a long line, but more like one word ?

**Comment by Micha-he** [comment]
Now (see #131) I can live with 'edit/select word'. But a 'long touch on screen' would be great.
This also clears the question of marking a longer text. This works also...
