### ISSUE TITLE
Add access Termux home directory

### ISSUE THREAD

**Issue by IshanKBG** [deadlyjack/code-editor#133]
Can you add a feature in which we can access Termux home directory files and edit the code files such as .cpp
It is pain to copy paste everytime while running c++ with ACode
I am also not interested in rooting my device

**Comment by chiaravalle** [comment]
Yes, I'd like this too

**Comment by ccamiloo** [comment]
Currently it is posible, just follow the next steps:

- Click in the three dots menu and tap add folder

- Tap in the '+' sign at the top right.

- In the name you can put 'termux directory' or whatever you like to name the folder

- Click select path and choose termux from the sidebar menu, now tap select and you will have access to termux directory :)


I think @deadlyjack should close this issue

**Comment by chiaravalle** [comment]
@ccamiloo great, very nice! Did it.
I'm still missing compilators/debuggers support, but I guess it's too much work to have even a little of it.
