### ISSUE TITLE
Physical keyboard issue 

### ISSUE THREAD

**Issue by Niskill2** [deadlyjack/code-editor#145]
Like i said above i have some trouble with the editor and my physical keyboard. Software is running on huawei matepad pro, with the original huawei keyboard. I cant type the "}" closing bracket.. 
All other alt bindings are working perfectly. 
I also tested it with gboard and hackers keyboard 
but its also not working. 
Maybe you can fix this bug? :)

**Comment by deadlyjack** [comment]
Can you provide more information about the device, app and keyboard. Also attach some screenshots or screen recording.

**Comment by Niskill2** [comment]
Soo, the device im working with is a Huawei Matepad Pro (Android 10-EMUI 10.1.0).
And the machanical keyboard is also from Huawei (original-with german layout)
I'm using the Acode pro app (1.1.14.139).
I can send later some Screenshots but the problem wont be visible, every other Alt GR (English => Ctrl + Alt) Binding is working perfectly.
The only one i have trouble with is the "}" curved closing Bracket...
"Alt Gr+ 0" doesnt have any effect ..

**Comment by deadlyjack** [comment]
Check [this](https://github.com/LightTable/LightTable/issues/270) issue on Ace Editor repo.
