### ISSUE TITLE
Specify github token

### ISSUE THREAD

**Issue by Amplifi-Beats** [deadlyjack/code-editor#179]
Tell the user what permissions acode needs? Amazing application btw, having multiple files open is brilliant!

**Comment by deadlyjack** [comment]
Thank you for the suggestion. I'll describe what permissions are needed and how to create token. I'm working on feature to open multiple file in split screen for wider screen.

**Comment by deadlyjack** [comment]
Done! It will be available in version (1.3.144). Thank you for your suggestion.

**Comment by washingtonsteven** [comment]
Hi, I have version 1.6.0 but I don't see instructions in app on what permission the token needs. Was this removed somehow? I am unwilling to grant the app full permission to my Github account.

**Comment by eclecticpassions** [comment]
Sorry to bring up old thread. I'm on 1.8.6, without any mention or details on what permissions to include for generating a personal access token to use the github plugin in Acode. Can anyone give some guidance? Thanks.
