### ISSUE TITLE
Text files not visible in Acode's internal file browser

### ISSUE THREAD

**Issue by lubieowoce** [deadlyjack/code-editor#185]
```
Acode version: 1.2.143
Android version: 11
SDK: 30
Device: Pixel 4a (sunfish)
ISA: arm64-v8a
```
When opening a file using Acode's browser  (` ⋮ ` → "Open file" → "Internal storage"), only image files are shown – all other files are hidden, even when "show hidden files" is enabled.

e.g. if i have a folder like this:
```
  foo.txt
  bar.jpg
  quux.tsv
  zap.svg
```
  
the browser only shows

```
  bar.jpg
  zap.svg
```

The same thing happens with the sidebar view from "Open folder".

screenshots:

### 1. test folder in a file browser app (Amaze)

![Screenshot_20210419-131228](https://user-images.githubusercontent.com/13698226/115227940-6c64e680-a111-11eb-8fb0-498f8fc8b94a.png)

### 2. test folder in Acode's browser

![Screenshot_20210419-131549](https://user-images.githubusercontent.com/13698226/115228003-81417a00-a111-11eb-8986-74a85b45686c.png)

**Comment by lubieowoce** [comment]
looks like Android distinguishes ["media files"](https://developer.android.com/training/data-storage/shared/media) and ["documents and other files"](https://developer.android.com/training/data-storage/shared/documents-files). (there's a nice table over [here](https://developer.android.com/training/data-storage)), and for some reason Acode's browser only shows "media files". This might be an issue with requesting the wrong permission -- the permission management screen shows this:

![Screenshot_20210429-153710](https://user-images.githubusercontent.com/13698226/116559618-eb6fd100-a900-11eb-8c01-6e3627e169bd.png)

note that there's no way to grant access to "documents and other files". i'm guessing something changed re: filesystem permissions and access to "documents and other files" requires something else now.

**Comment by deadlyjack** [comment]
Try to add the internal storage manually using option 'Add path'.
Steps to add storage manually:
1. Tap on '+' icon to top right corner
2. Select option 'Add path'
3. Select 'Internal Storage' from document provider. If internal storage is not visible, check option 'Show internal storage' from hamburger menu
4. Tap on bottom button with text 'select this folder'
5. Now check if your files are visible or not.

**Comment by lubieowoce** [comment]
thank you, that worked! would have never figured it out myself though :) IMO this should be in the FAQ or even in the app (i'm thinking a tiny banner in the browser that's like "Files not showing?" or something). and ideally, the user wouldn't have to worry about this at all (but idk how much work that would be or how annoying dealing with permissions is)

anyway this workaround is good enough for me, feel free to close this issue if you don't plan on working on this

**Comment by deadlyjack** [comment]
Welcome 🤗. It's a Cordova project because of it I cannot modify Android services/permissions directly, for that I've the modify the specific cordova plugin or sometime I've create whole plugin from scratch of it isn't available on internet.

Anyway I'll look into the issue and try to fix it. I'll decide later whether it's fixable or not.

**Comment by deadlyjack** [comment]
Fixed in latest version of Acode.
