### ISSUE TITLE
How could I make my own theme?

### ISSUE THREAD

**Issue by asxlvm** [deadlyjack/code-editor#187]
I want to have Ayu Mirage in this app, it looks something like this;
![IMG_20210428_213751](https://user-images.githubusercontent.com/81298611/116462754-1d822400-a86a-11eb-8f01-c51f33a29661.jpg)

I would want to have an option to make my own themes and if there would not be one, atleast document how to add your own theme using the source and then building the app.

**Comment by deadlyjack** [comment]
You can add your own theme in https://github.com/deadlyjack/code-editor/blob/master/src/styles/themes.scss
