### ISSUE TITLE
Add exit button

### ISSUE THREAD

**Issue by jidanni** [deadlyjack/code-editor#189]
Add an exit button or an exit menu item. Or call it quit. The purpose is for older users who can't seem to find the proper way to exit even though there is another better way.

**Comment by jidanni** [comment]
Another great use of this button would be, for instance we launched the Android file manager, which the launched this app.  But now there is no way to launch the file manager again without first exiting this app... yes, even though there is a better way. However might need to ask on some discussion list what the better way is. That might take several hours.

**Comment by deadlyjack** [comment]
Thanks for suggestion. This will be added to next update.

**Comment by deadlyjack** [comment]
Added an exit option in the menu and will be available in version (1.3.144)
