### ISSUE TITLE
Have a message confirming saves

### ISSUE THREAD

**Issue by jidanni** [deadlyjack/code-editor#206]
When we select the word Save from the menu, maybe the file is saved. Well it would be clearer if there was a message on the screen that says "saved successfully".

**Comment by RoHBee** [comment]
Theres a dot on the icon of the file if it is not saved. So, once saved the dot is hidden. 🙂
![IMG_20210508_181939](https://user-images.githubusercontent.com/64386226/117539376-10afbe00-b02a-11eb-8efa-cee813778e41.jpg)

**Comment by jidanni** [comment]
In Emacs' *messages* buffer:

> Saving file /tmp/z...
> Wrote /tmp/z
> Saving file /tmp/z...
> Wrote /tmp/z

So I would, in addition to your dot, have a "toast": _Wrote /tmp/z_.

**Comment by RoHBee** [comment]
The project is open source go make your own toast. 😂
