### ISSUE TITLE
console.time is not a function.

### ISSUE THREAD

**Issue by RoHBee** [deadlyjack/code-editor#207]
The console has no property ```time```.
![IMG_20210508_182920](https://user-images.githubusercontent.com/64386226/117539671-68025e00-b02b-11eb-9e3c-6053d97678de.jpg)

**Comment by deadlyjack** [comment]
Thanks for reporting this. I've added this method and it will be available in next update.

**Comment by RoHBee** [comment]
> Thanks for reporting this. I've added this method and it will be available in next update.

Why don't you use eruda instead of console?
https://eruda.liriliri.io/
