### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by dz-id** [deadlyjack/code-editor#219]
![IMG_20210717_231908](https://user-images.githubusercontent.com/52864765/126043526-652cc690-01a4-4011-9ced-cdd140f4f635.jpg)

Hi, I'm using Acode Premium but when I use home termux as an open folder, I have a fileNotFoundException error when deleting a file/folder, and I'm sure that the file/folder exists

the error only occurs when using home termux as an open folder.

when using local sdcard it's no problem no error all fine.

Sorry if my language is not good, I wrote this with the help of google translate, and I can't speak English.

**Comment by dz-id** [comment]
![IMG_20210717_233342](https://user-images.githubusercontent.com/52864765/126043711-68884538-b8c5-40c8-998b-70014559c496.jpg)

Not only that, sometimes when you want to move files/folders or rename files/folders you also experience errors.

**Comment by deadlyjack** [comment]
There is limitations when using Termux directory. There is nothing that can be done. Use termux to rename and delete file/direcotry.
