### ISSUE TITLE
Dracula theme highlight bug

### ISSUE THREAD

**Issue by calheiros** [deadlyjack/code-editor#22]
The html tags are not being highlighted with the Dracula theme. This is my favorite theme, with this bug it is difficult to work with HTML.

![Screenshot_2020-04-24-21-41-18](https://user-images.githubusercontent.com/20629241/80267121-e9cc5700-8675-11ea-9cfd-71832b80d62c.png)

**Comment by deadlyjack** [comment]
Fixed in version 0.1.11.103.

**Comment by calheiros** [comment]
@deadlyjack thank you so much!
