### ISSUE TITLE
Open arbitrary files

### ISSUE THREAD

**Issue by DUOLabs333** [deadlyjack/code-editor#226]
When I want to open an eg. mp3 as a text file, Acode refuses it, saying it doesn't support mp3 files. This is true even for files like ttml, as it keeps loading forever, never opening it. Is there a way to allow Acode to open whatever file I want as a text file? I tried editing the settings.json file with the filesNotAllowed property, but it didn't work.

**Comment by deadlyjack** [comment]
I've tried the what you have written and it's working for me. If can you share more details about the file you are trying to load?

**Comment by deadlyjack** [comment]
Yes, I was able to load binary files after editing settings.

**Comment by DUOLabs333** [comment]
What settings?

**Comment by deadlyjack** [comment]
Editor settings. Opened by tapping 'edit' icon on top right corner in settings.
