### ISSUE TITLE
Cannot save file after minimizing app for 50 or more minutes.

### ISSUE THREAD

**Issue by rock112293** [deadlyjack/code-editor#24]
Bugs found when open and close the application.
no dot on save icon when you change the code.
slow loading feature...
please regards this issue to further or next update.

**Comment by mzaini30** [comment]
> Bugs found when open and close the application.
> no dot on save icon when you change the code.
> slow loading feature...
> please regards this issue to further or next update.

Can you send a screenshot?

**Comment by rock112293** [comment]
i send the screenshot when i encounter again...my solution is uninstall the
app and reinstall again.The bugs will fix again but i monitor check all
features and wait to encounter again the bugs
thanks for reply.
Godspeed!

**Comment by deadlyjack** [comment]
Please can you provide more details on the issue.

**Comment by rock112293** [comment]
When apps is minimize for 50 minutes and after i return to open again and preview the code i can't save because of bug.
