### ISSUE TITLE
Cannot Push to GitHub

### ISSUE THREAD

**Issue by knary** [deadlyjack/code-editor#27]
I can edit a file from my GitHub repo, but when I try to save it, the API call fails with a 404 like:

Error: 404 error making request put https://api.github.com/repos/knary/knary.github.io/contents/knary.github.io/knary.github.io/index.html: "Not Found"

Reproducible with Gists:

Error: 404 error making request patch https://api.github.com/gists/c01e264c436dc77d1e5ed343cec5d830: "Not Found"

**Comment by deadlyjack** [comment]
Path is repeating '/knary.github.io/knary.github.io/' which is causing the error. Please can you provide steps to generate this error.

**Comment by knary** [comment]
I am getting the same issue with my other repositories:

Error: 404 error making request put https://api.github.com/repos/knary/workout/contents/LICENSE: "Not Found"

Steps to reproduce:
1. Open the right overflow menu.
2. Select "GitHub"
3. Authenticate with a token
4. Tap "📒 Repositories"
5. Select a repo
6. Select a branch (Dev)
7. Select a file
8. Add a new line to the file
9. Tap 💾 at the bottom of the screen
10. Tap OK in the commit pop-up

**Comment by deadlyjack** [comment]
I've tried to regenerate this bug, but unable to! Are you still facing this issue?

**Comment by knary** [comment]
I am still facing the issue. Would pulling logs off of my phone help?

I haven't done Android dev in many years, so what is the current best practice for getting logs?

**Comment by deadlyjack** [comment]
Hi can try it again with latest version i.e. 0.1.13.107 from play store.

**Comment by knary** [comment]
Yep, able to reproduce on 0.1.13.107

**Comment by deadlyjack** [comment]
I sm going to fork your repository to test what's going wrong.

**Comment by knary** [comment]
Still seeing the issue in 0.1.13.108

**Comment by deadlyjack** [comment]
I forked you repo and try to edit it using Acode and it's working perfectly. I cannot fix this it because I am unable to generate this issue.
