### ISSUE TITLE
FTP doesn't connect on my Samsung Galaxy s7 

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/code-editor#28]
I get this error whenever I try opening logging into FTP sever:
`cannot connect to ftp: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String it.sauronsoftware.ftp4j.FTPClient.getUsername()' on a null object reference`
![Screenshot_20200426-103029_Acode](https://user-images.githubusercontent.com/34959120/80477886-9ba0a780-8944-11ea-87d2-5d0ec4c8a92f.jpg)

Sometimes it simply says `can't open connection`
![Screenshot_20200426-102023_Acode](https://user-images.githubusercontent.com/34959120/80478025-ce4aa000-8944-11ea-8958-701555778853.jpg)

The getUsername() method only works if authentication is successful, it returns the username. In my case, I think it tries to fetch my username while I'm not authenticated.

**Comment by PatAbah** [comment]
Kind of weird, but I changed my SIM (service provider) and everything now works fine.

**Comment by deadlyjack** [comment]
@PatAbah That's really weird 😂.
