### ISSUE TITLE
Copy/Paste Function on FTP not working

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/code-editor#30]
1. Open an ftp folder
2. Long press a folder/file name
3. Select Copy 
4. Long press another folder
5. Select paste 
You'll get the message:
`ERROR
Copy command is supported by FTP`

At a point I wondered if it meant IS NOT supported instead of IS supported. 
![20200501_145042](https://user-images.githubusercontent.com/34959120/80810415-b3ce2c00-8bbb-11ea-9165-9e3735dbfc7d.jpg)

ALSO, BTW, it works as expected for files/folders on local machine but it displays "error" in the toast() message when complete.

**Comment by deadlyjack** [comment]
Ah! My mistake. Thank you for pointing it out. It was meant to be 'is not'.
