### ISSUE TITLE
[Feature Request] - Toggle Haptic Feedback

### ISSUE THREAD

**Issue by veeshi** [deadlyjack/code-editor#31]
Clicking on any bottom action bar button causes the phone to vibrate. While this is useful in certain scenarios, it would be better if we can toggle the vibration on and off and also set the vibration strength.

**Comment by deadlyjack** [comment]
@veeshi It will be available in next version

**Comment by deadlyjack** [comment]
Fixed in beta branch and will be available soon in master.
