### ISSUE TITLE
FTP Error : Read Time Out

### ISSUE THREAD

**Issue by RinoPuji** [deadlyjack/code-editor#33]
Hi deadlyjack,
I wan to report problem about ftp.When i click on ftp connection,what i got is : 

`"ERROR java.net.SocketTimeOutExeption:Read time out"`

At first i thought the problem is from my webhosting provider,so i try it with my desktop via file zilla and it work.I also try using other code editor application that support ftp and it also work.

That all for my report.
Thank you.

![Screenshot_2020-05-07-03-38-56-524_com foxdebug acodefree](https://user-images.githubusercontent.com/44793170/81220699-55b6a400-9014-11ea-94b3-46eb1860f7a1.jpg)

**Comment by deadlyjack** [comment]
Please may I know which version of the app you are?

**Comment by RinoPuji** [comment]
I am using free version 0.1.11.103 from playstore.

![Screenshot_2020-05-07-03-47-57-275_com miui securitycenter](https://user-images.githubusercontent.com/44793170/81221583-9f53be80-9015-11ea-976b-a4a77dde5218.jpg)

**Comment by deadlyjack** [comment]
In the first screen shot I noticed that you are using 000webhost. I have also tried 000webhost but itt didn't work because it's very very slow. This problem only happens in 000webhost. I recommend you to use byethost (free) it works perfectly. But I'll try to fix the issue.

**Comment by RinoPuji** [comment]
After following your suggestion by using byethost,the ftp is work.I also trying using ionos and it work.

In the end,the problem is came from 000webhost because the connection is slow.

I am sorry for taking your time and thank you for you help.
