### ISSUE TITLE
[Feature request]- Remembering type of syntax highlighting of unsual file extension

### ISSUE THREAD

**Issue by drtritm** [deadlyjack/code-editor#36]
It will be really convenient that it can remember the type of syntax highlighting of some unsual extension files. I usually work with these files so I have to keep changing the type of syntax highlighting to the one i want to use.

**Comment by deadlyjack** [comment]
Sure, It will available in next version.

**Comment by deadlyjack** [comment]
Added in version 0.1.14.109 and will be available on play store soon.
