### ISSUE TITLE
Web preview not working.

### ISSUE THREAD

**Issue by rock112293** [deadlyjack/code-editor#37]
The web preview not work only loading stage I can see.
Both free and paid apps.
Version:version 0.1.12.105
I have proof.
Please email me to this problem.
I can't use both free and paid version.

**Comment by deadlyjack** [comment]
Please can you share the details (proof) here!

**Comment by rock112293** [comment]
Ok I will sent the screenshot

On May 13, 2020 3:17 PM, "Ajit Kumar" <notifications@github.com> wrote:

Please can you share the details (proof) here!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deadlyjack/code-editor/issues/37#issuecomment-627796707>,
or unsubscribe

**Comment by rock112293** [comment]
On May 13, 2020 3:39 PM, "Rocky Francisco" <rock112293@gmail.com> wrote:

Ok I will sent the screenshot


On May 13, 2020 3:17 PM, "Ajit Kumar" <notifications@github.com> wrote:

Please can you share the details (proof) here!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deadlyjack/code-editor/issues/37#issuecomment-627796707>,
or unsubscribe

**Comment by rock112293** [comment]
![Screenshot_20200513-145702](https://user-images.githubusercontent.com/62177410/81786453-4367c900-9532-11ea-9f6d-049

**Comment by rock112293** [comment]
![Screenshot_20200513-145702](https://user-images.githubusercontent.com/62177410/81786592-7ad67580-9532-11ea-8cf8-c2cde3cf1cd7.jpg)
