### ISSUE TITLE
Writing Multiple places

### ISSUE THREAD

**Issue by Vinayakweb** [deadlyjack/code-editor#39]
**how to write at two places at same time 
What is keyboard shortcut.**

> Please tell keyboard shortcut

**LIKE THIS -**

![1589633448374](https://user-images.githubusercontent.com/62464381/82120217-2e916c80-97a2-11ea-8246-0eb4698523cc.jpg)

**Comment by deadlyjack** [comment]
If you have physical mouse and keyboard you ctrl+click for multiple cursor. You can also use keyboard shortcuts using Hacker's keyboard i.e. ctrl+alt+arrows key.
