### ISSUE TITLE
[Feature Request] quick tools button

### ISSUE THREAD

**Issue by inspir3dArt** [deadlyjack/code-editor#57]
When I write code on my smartphone in landscape mode, I have the quick tools menu bar disabled, because with this extra menu bar I can only see 4 lines of code in the editor. 

It would be nice to have a button with the most important tools ( like undo and redo) in the top menu bar, when the quick tools bar is disabled.

**Comment by deadlyjack** [comment]
I am working on it. I'll update here when it's completed.
