### ISSUE TITLE
[Feature Request] Option to set a default Workspace Folder

### ISSUE THREAD

**Issue by inspir3dArt** [deadlyjack/code-editor#59]
A option to set a default workspace folder, that get opened in the file browser if I klick "Open Folder" would be nice.

**Comment by deadlyjack** [comment]
Now you can set bookmark to any path in Acode which will be handy and likely be the feature for this request. Refer this YouTube video https://youtu.be/0GFUHFq8VqE

**Comment by emiliobog** [comment]
@deadlyjack uwu
