### ISSUE TITLE
[Suggestion] Add option to turn off auto-correction

### ISSUE THREAD

**Issue by yodrew** [deadlyjack/code-editor#67]
Sometimes it is good. For me as a prose writer, it is a distraction. Sometimes turning it off in keyboard settings doesn't work. 

Edit: This would include turning off the suggestion pop-up window. 

Thank you!

**Comment by wagnered** [comment]
I agree with @yodrew.

It just gets in the way and seems to capture the up/down arrows so I can't move from line to line. Otherwise it's an excellent product.
