### ISSUE TITLE
Backspace cannot delete newlines in AOSP keyboard.

### ISSUE THREAD

**Issue by alissonlauffer** [deadlyjack/code-editor#7]
Demo:
https://imgur.com/BfTk5l8

**Comment by deadlyjack** [comment]
I don't know the problem with ASOP keyboard. It send wierd keyboard event (sometimes multiple keyboards events) on pressing enter key, which cause this problem because of that 'backspace' will not work for few time or entirely. I am unable to solve this problem for long time.

**Comment by alissonlauffer** [comment]
Now I realized this is an Ace issue.
I have just created an issue there: https://github.com/ajaxorg/ace/issues/4212

I will keep you track of the status here.

**Comment by alissonlauffer** [comment]
Fixed in 0.0.9.90
