### ISSUE TITLE
[bug] Renaming Files

### ISSUE THREAD

**Issue by inspir3dArt** [deadlyjack/code-editor#71]
If you rename a file and then try to rename it back, acode throws the error "File not found". To reproduce:
index.html -> index.htm -> index.html

**Comment by inspir3dArt** [comment]
It looks like it can only be reproduced if you used the full path to open the projects folder. I can't reproduce it if I used a bookmark.

**Comment by deadlyjack** [comment]
Thanks for reporting this bug. I'll fix it soon.
