### ISSUE TITLE
Files auto reloading from disk.

### ISSUE THREAD

**Issue by Ahmard** [deadlyjack/code-editor#74]
File reloading from disk shouldn't be automatically, it causes users to loose some portion of their code, a prompt should be shown to user with a message something like "File x has been changed do you want to reload it?"
Let users acknowledge the changes manually.
Thank you.

**Comment by deadlyjack** [comment]
It should work that way, if it not showing there must be a issue. I'll check it fix it.

**Comment by deadlyjack** [comment]
Hi, I've fixed it. If your file in unsaved and file content is changed then it ask to reload the file.

**Comment by Ahmard** [comment]
Okay, thank you.
