### ISSUE TITLE
SHFT Button Misbehaving 

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/code-editor#82]
In previous versions, activating the SHFT button starts highlighting text from the current position upto new cursor position. Not anymore... It just selects stuff randomly now.

**Comment by deadlyjack** [comment]
@PatAbah This bug is caused by new update. I'll fix it soon.

**Comment by deadlyjack** [comment]
I've fixed this issue. Thank you for reporting it.

**Comment by PatAbah** [comment]
Great!
