### ISSUE TITLE
Error while opening Termux File System

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/code-editor#83]
After the recent update, I've tried opening my Termux folder... I get this error message: `Permission Denial: opening provider com.termux.filepicker.TermuxDocumentsProvider from ProcessRecord{1ecc05fd0 4715:com.foxdebug.acodefree/u0a248} (pid=4715, uid=10248) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs`

Consequently, I'm unable to edit any of my files generated by Termux. I added the Termux directory normally from
- menu > add folder > plus icon > add path

**Comment by deulizealand** [comment]
@PatAbah Maybe you should chmod you file first. ? #cmiiw

**Comment by PatAbah** [comment]
I removed the folder, added it again and it now opens.
