### ISSUE TITLE
The text wrap setting is not honored after restart

### ISSUE THREAD

**Issue by KentVu** [deadlyjack/code-editor#9]
Prerequisites:
- The text wrap setting is `no` .

Steps to produce:
1. Set `text wrap`  setting to `yes` .
      The setting is reflected.
1. Now kill the app, (swipe up the app from the recent activity)
1. Open it again.
     Now even though the setting is `Yes`, it's not reflecting on the editor.

**Comment by deadlyjack** [comment]
This issue is fixed in v 0.0.8.89
