### ISSUE TITLE
ftpd: no such file

### ISSUE THREAD

**Issue by Rynni** [deadlyjack/code-editor#90]
Hello,

Everytime i'm typing following Code: "tcpsvd -vE 0.0.0.0 1024 ftpd -w $HOME/projects" i get this:

tcpsvd: listening on 0.0.0.0:1024, starting
tcpsvd: start 17016 127.0.0.1:1024-127.0.0.1:36504
tcpsvd: can't execute 'ftpd': No such file or directory
tcpsvd: status 1/30
tcpsvd: end 17016 exit 127
tcpsvd: status 0/30

Want to use Acode with Termux as Terminal.

Thanks

**Comment by I-am-Orion** [comment]
How to fix this?
