### ISSUE TITLE
[Bug] Fix line height in editor

### ISSUE THREAD

**Issue by dayfuaim** [deadlyjack/code-editor#92]
I use Acode on tablet.
Font size 12px is too small to use.

But with any font size (except for 12px), I get every line cut on top.

Size: 14px
![20200816_165637](https://user-images.githubusercontent.com/1274699/90336017-b5dcbf00-dfe1-11ea-8a7c-6df801440ab7.jpg)

Size: 16px
![Screenshot_20200816-165958_Acode](https://user-images.githubusercontent.com/1274699/90336054-f1778900-dfe1-11ea-90ba-3418df30a78f.jpg)

Please fix it.
Make line height calculated from font-size.

**Comment by deadlyjack** [comment]
I've fixed it in latest version 1.1.14.126
