### ISSUE TITLE
Dangerous Bug in SHFT Shortcut Key 

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/code-editor#99]
Version: 1.1.14.125
Device: SM-N935F
Manufacturer: samsung
Android version: 9
Info: Buggy SHFT key

Hi there! 

There's a serious bug (with the SHFT key) I'll like to report.

Here's how to recreate it:

In a new file, type "this is line 1"

Next, type "this is line 2"

In the third line type "this is line 1" (not 3)

Now, place the cursor at the end of the first line, and activate SHFT. Then, place the cursor at the beginning of the same line (thereby highlighting it) 

While highlighted by SHFT, any changes you make (for example, deleting the line —or cutting it) will affect line 3 (because it's identical!) 

In a file of hundreds of lines, this won't be noticed, and will cause severe issues for the developer. 

I look forward to this being fixed. Thanks.

![Screenshot_20200927-112323_Acode](https://user-images.githubusercontent.com/34959120/94362529-e0776880-00b3-11eb-805e-d890f2fa5e64.jpg)

As seen in the image above, multiple cursors now appear in the editor. Even if there are a hundred identical lines, a hundred cursors appear and editing any simultaneously edits all!

**Comment by deadlyjack** [comment]
Thank you for reporting this bug. I was able to reproduce it. I'll fix it soon.

**Comment by deadlyjack** [comment]
Fixed!
